# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='delete_flag',
            field=models.CharField(default='1', max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7'),
        ),
    ]
